<template>
  <div :class="{'has-logo':showLogo}">
    <logo v-if="showLogo" :collapse="isCollapse" />
    <el-scrollbar wrap-class="scrollbar-wrapper">
      <el-menu :default-active="activeMenu" :collapse="isCollapse" :background-color="variables.menuBg" :text-color="variables.menuText" :unique-opened="false" :active-text-color="variables.menuActiveText" :collapse-transition="false" mode="vertical" @select="toPage">
        <sidebar-item v-for="(menu, index) in menuList" :key="index + '1000'" :item="menu" />
      </el-menu>
    </el-scrollbar>
  </div>
</template>

<script>
import { mapGetters } from 'vuex'
import Logo from './Logo'
import SidebarItem from './SidebarItem'
import variables from '@/styles/variables.scss'
export default {
  components: { Logo, SidebarItem },
  data() {
    return {
      menuList: []
    }
  },
  computed: {
    ...mapGetters([
      'permission_routes',
      'sidebar'
    ]),
    activeMenu() {
      const route = this.$route
      const { meta, path } = route
      if (meta.activeMenu) {
        return meta.activeMenu
      }
      return path
    },
    showLogo() {
      return this.$store.state.settings.sidebarLogo
    },
    variables() {
      return variables
    },
    isCollapse() {
      return !this.sidebar.opened
    }
  },
  mounted() {
    this.getMenuInfo()
  },
  methods: {
    toPage(index, indexPath) {
      this.$router.push(index)
    },
    getMenuInfo() {
      const pageShow = {
        'searchValue': null,
        'createBy': null,
        'createTime': '2020-11-11 11:37',
        'updateBy': null,
        'updateTime': null,
        'remark': null,
        'params': null,
        'delFlag': null,
        'menuId': 1,
        'menuName': '页面示例',
        'parentId': 1,
        'menuLevel': null,
        'orderNum': '0',
        'url': '#1',
        'menuType': '0',
        'icon': 'el-icon-apple',
        'children': [
          // {
          //   'searchValue': null,
          //   'createBy': null,
          //   'createTime': null,
          //   'updateBy': null,
          //   'updateTime': null,
          //   'remark': null,
          //   'params': null,
          //   'delFlag': null,
          //   'menuId': 4,
          //   'menuName': '用户管理',
          //   'parentId': 3,
          //   'menuLevel': null,
          //   'orderNum': '1',
          //   'url': '/systemManage/userManage',
          //   'menuType': '0',
          //   'icon': null,
          //   'children': []
          // }, {
          //   'searchValue': null,
          //   'createBy': null,
          //   'createTime': null,
          //   'updateBy': null,
          //   'updateTime': null,
          //   'remark': null,
          //   'params': null,
          //   'delFlag': null,
          //   'menuId': 5,
          //   'menuName': '角色管理',
          //   'parentId': 3,
          //   'menuLevel': null,
          //   'orderNum': '2',
          //   'url': '/systemManage/roleManage',
          //   'menuType': '0',
          //   'icon': null,
          //   'children': []
          // },
          {
            'searchValue': null,
            'createBy': null,
            'createTime': null,
            'updateBy': null,
            'updateTime': null,
            'remark': null,
            'params': null,
            'delFlag': null,
            'menuId': 6,
            'menuName': 'TEST',
            'parentId': 1,
            'menuLevel': null,
            'orderNum': '4',
            'url': '/systemManage/ceshi',
            'menuType': '0',
            'icon': null,
            'children': []
          }, {
            'searchValue': null,
            'createBy': null,
            'createTime': null,
            'updateBy': null,
            'updateTime': null,
            'remark': null,
            'params': null,
            'delFlag': null,
            'menuId': 1223,
            'menuName': 'TEST2',
            'parentId': 1,
            'menuLevel': null,
            'orderNum': '4',
            'url': '/systemManage/ceshi2',
            'menuType': '0',
            'icon': null,
            'children': []
          }]
      }
      const pageComponents = {
        'searchValue': null,
        'createBy': null,
        'createTime': '2020-11-11 11:37',
        'updateBy': null,
        'updateTime': null,
        'remark': null,
        'params': null,
        'delFlag': null,
        'menuId': 2,
        'menuName': '组件仓库',
        'parentId': 2,
        'menuLevel': null,
        'orderNum': '5',
        'url': '#2',
        'menuType': '0',
        'icon': 'el-icon-cherry',
        'children': [{
          'searchValue': null,
          'createBy': null,
          'createTime': null,
          'updateBy': null,
          'updateTime': null,
          'remark': null,
          'params': null,
          'delFlag': null,
          'menuId': 7,
          'menuName': '表格',
          'parentId': 2,
          'menuLevel': null,
          'orderNum': '6',
          'url': '/systemManage/table',
          'menuType': '0',
          'icon': null,
          'children': []
        }]
      }
      const pageVue = {
        'searchValue': null,
        'createBy': null,
        'createTime': '2020-11-11 11:37',
        'updateBy': null,
        'updateTime': null,
        'remark': null,
        'params': null,
        'delFlag': null,
        'menuId': 3,
        'menuName': 'VUE',
        'parentId': 1,
        'menuLevel': null,
        'orderNum': '5',
        'url': '#3',
        'menuType': '0',
        'icon': 'el-icon-pear',
        'children': [{
          'searchValue': null,
          'createBy': null,
          'createTime': null,
          'updateBy': null,
          'updateTime': null,
          'remark': null,
          'params': null,
          'delFlag': null,
          'menuId': 3001,
          'menuName': '父子传值',
          'parentId': 999,
          'menuLevel': null,
          'orderNum': '6',
          'url': '/systemManage/VueChuanzhi',
          'menuType': '0',
          'icon': null,
          'children': []
        }, {
          'searchValue': null,
          'createBy': null,
          'createTime': null,
          'updateBy': null,
          'updateTime': null,
          'remark': null,
          'params': null,
          'delFlag': null,
          'menuId': 3002,
          'menuName': '自定义指令',
          'parentId': 3,
          'menuLevel': null,
          'orderNum': '6',
          'url': '/systemManage/directivesDemo',
          'menuType': '0',
          'icon': null,
          'children': []
        }, {
          'searchValue': null,
          'createBy': null,
          'createTime': null,
          'updateBy': null,
          'updateTime': null,
          'remark': null,
          'params': null,
          'delFlag': null,
          'menuId': 3003,
          'menuName': 'VUEX',
          'parentId': 3,
          'menuLevel': null,
          'orderNum': '6',
          'url': '/systemManage/VueX',
          'menuType': '0',
          'icon': null,
          'children': []
        }, {
          'searchValue': null,
          'createBy': null,
          'createTime': null,
          'updateBy': null,
          'updateTime': null,
          'remark': null,
          'params': null,
          'delFlag': null,
          'menuId': 3022,
          'menuName': 'Vue-i18n',
          'parentId': 3,
          'menuLevel': null,
          'orderNum': '6',
          'url': '/systemManage/Vue-i18n',
          'menuType': '0',
          'icon': null,
          'children': []
        }, {
          'searchValue': null,
          'createBy': null,
          'createTime': null,
          'updateBy': null,
          'updateTime': null,
          'remark': null,
          'params': null,
          'delFlag': null,
          'menuId': 3004,
          'menuName': 'LESS',
          'parentId': 3,
          'menuLevel': null,
          'orderNum': '6',
          'url': '/systemManage/less',
          'menuType': '0',
          'icon': null,
          'children': []
        }, {
          'searchValue': null,
          'createBy': null,
          'createTime': null,
          'updateBy': null,
          'updateTime': null,
          'remark': null,
          'params': null,
          'delFlag': null,
          'menuId': 3005,
          'menuName': 'es601',
          'parentId': 3,
          'menuLevel': null,
          'orderNum': '6',
          'url': '/systemManage/es601',
          'menuType': '0',
          'icon': null,
          'children': []
        }, {
          'searchValue': null,
          'createBy': null,
          'createTime': null,
          'updateBy': null,
          'updateTime': null,
          'remark': null,
          'params': null,
          'delFlag': null,
          'menuId': 3006,
          'menuName': 'es602',
          'parentId': 3,
          'menuLevel': null,
          'orderNum': '6',
          'url': '/systemManage/es602',
          'menuType': '0',
          'icon': null,
          'children': []
        }, {
          'searchValue': null,
          'createBy': null,
          'createTime': null,
          'updateBy': null,
          'updateTime': null,
          'remark': null,
          'params': null,
          'delFlag': null,
          'menuId': 3007,
          'menuName': 'es603',
          'parentId': 3,
          'menuLevel': null,
          'orderNum': '6',
          'url': '/systemManage/es603',
          'menuType': '0',
          'icon': null,
          'children': []
        }, {
          'searchValue': null,
          'createBy': null,
          'createTime': null,
          'updateBy': null,
          'updateTime': null,
          'remark': null,
          'params': null,
          'delFlag': null,
          'menuId': 3008,
          'menuName': 'animation1',
          'parentId': 3,
          'menuLevel': null,
          'orderNum': '6',
          'url': '/systemManage/animation1',
          'menuType': '0',
          'icon': null,
          'children': []
        }, {
          'searchValue': null,
          'createBy': null,
          'createTime': null,
          'updateBy': null,
          'updateTime': null,
          'remark': null,
          'params': null,
          'delFlag': null,
          'menuId': 3009,
          'menuName': 'animation2',
          'parentId': 3,
          'menuLevel': null,
          'orderNum': '6',
          'url': '/systemManage/animation2',
          'menuType': '0',
          'icon': null,
          'children': []
        }, {
          'searchValue': null,
          'createBy': null,
          'createTime': null,
          'updateBy': null,
          'updateTime': null,
          'remark': null,
          'params': null,
          'delFlag': null,
          'menuId': 3016,
          'menuName': 'Table1',
          'parentId': 3,
          'menuLevel': null,
          'orderNum': '6',
          'url': '/systemManage/table1',
          'menuType': '0',
          'icon': null,
          'children': []
        }, {
          'searchValue': null,
          'createBy': null,
          'createTime': null,
          'updateBy': null,
          'updateTime': null,
          'remark': null,
          'params': null,
          'delFlag': null,
          'menuId': 3017,
          'menuName': 'Table2',
          'parentId': 3,
          'menuLevel': null,
          'orderNum': '6',
          'url': '/systemManage/table2',
          'menuType': '0',
          'icon': null,
          'children': []
        }, {
          'searchValue': null,
          'createBy': null,
          'createTime': null,
          'updateBy': null,
          'updateTime': null,
          'remark': null,
          'params': null,
          'delFlag': null,
          'menuId': 3031,
          'menuName': 'Table3',
          'parentId': 3,
          'menuLevel': null,
          'orderNum': '6',
          'url': '/systemManage/table3',
          'menuType': '0',
          'icon': null,
          'children': []
        }, {
          'searchValue': null,
          'createBy': null,
          'createTime': null,
          'updateBy': null,
          'updateTime': null,
          'remark': null,
          'params': null,
          'delFlag': null,
          'menuId': 3032,
          'menuName': 'Table4',
          'parentId': 3,
          'menuLevel': null,
          'orderNum': '6',
          'url': '/systemManage/table4',
          'menuType': '0',
          'icon': null,
          'children': []
        }, {
          'searchValue': null,
          'createBy': null,
          'createTime': null,
          'updateBy': null,
          'updateTime': null,
          'remark': null,
          'params': null,
          'delFlag': null,
          'menuId': 3033,
          'menuName': 'Table5',
          'parentId': 3,
          'menuLevel': null,
          'orderNum': '6',
          'url': '/systemManage/table5',
          'menuType': '0',
          'icon': null,
          'children': []
        }, {
          'searchValue': null,
          'createBy': null,
          'createTime': null,
          'updateBy': null,
          'updateTime': null,
          'remark': null,
          'params': null,
          'delFlag': null,
          'menuId': 3066,
          'menuName': 'Mock1',
          'parentId': 3,
          'menuLevel': null,
          'orderNum': '6',
          'url': '/systemManage/mock1',
          'menuType': '0',
          'icon': null,
          'children': []
        }, {
          'searchValue': null,
          'createBy': null,
          'createTime': null,
          'updateBy': null,
          'updateTime': null,
          'remark': null,
          'params': null,
          'delFlag': null,
          'menuId': 3068,
          'menuName': 'Mock2',
          'parentId': 3,
          'menuLevel': null,
          'orderNum': '6',
          'url': '/systemManage/mock2',
          'menuType': '0',
          'icon': null,
          'children': []
        }]
      }
      const pageCharts = {
        'searchValue': null,
        'createBy': null,
        'createTime': '2020-11-11 11:37',
        'updateBy': null,
        'updateTime': null,
        'remark': null,
        'params': null,
        'delFlag': null,
        'menuId': 4,
        'menuName': 'echarts',
        'parentId': 1,
        'menuLevel': null,
        'orderNum': '0',
        'url': '#4',
        'menuType': '0',
        'icon': 'el-icon-grape',
        'children': [
          {
            'searchValue': null,
            'createBy': null,
            'createTime': null,
            'updateBy': null,
            'updateTime': null,
            'remark': null,
            'params': null,
            'delFlag': null,
            'menuId': 2001,
            'menuName': 'echarts-1',
            'parentId': 4,
            'menuLevel': null,
            'orderNum': '4',
            'url': '/charts/echartsOne',
            'menuType': '0',
            'icon': null,
            'children': []
          }, {
            'searchValue': null,
            'createBy': null,
            'createTime': null,
            'updateBy': null,
            'updateTime': null,
            'remark': null,
            'params': null,
            'delFlag': null,
            'menuId': 2002,
            'menuName': 'echarts-2',
            'parentId': 4,
            'menuLevel': null,
            'orderNum': '4',
            'url': '/charts/echartsTwo',
            'menuType': '0',
            'icon': null,
            'children': []
          }, {
            'searchValue': null,
            'createBy': null,
            'createTime': null,
            'updateBy': null,
            'updateTime': null,
            'remark': null,
            'params': null,
            'delFlag': null,
            'menuId': 2003,
            'menuName': 'echarts-3',
            'parentId': 4,
            'menuLevel': null,
            'orderNum': '4',
            'url': '/charts/echartsThree',
            'menuType': '0',
            'icon': null,
            'children': []
          }, {
            'searchValue': null,
            'createBy': null,
            'createTime': null,
            'updateBy': null,
            'updateTime': null,
            'remark': null,
            'params': null,
            'delFlag': null,
            'menuId': 2006,
            'menuName': 'echarts-4',
            'parentId': 4,
            'menuLevel': null,
            'orderNum': '4',
            'url': '/charts/echartsFour',
            'menuType': '0',
            'icon': null,
            'children': []
          }, {
            'searchValue': null,
            'createBy': null,
            'createTime': null,
            'updateBy': null,
            'updateTime': null,
            'remark': null,
            'params': null,
            'delFlag': null,
            'menuId': 2007,
            'menuName': 'echarts-5',
            'parentId': 4,
            'menuLevel': null,
            'orderNum': '4',
            'url': '/charts/echartsFive',
            'menuType': '0',
            'icon': null,
            'children': []
          }, {
            'searchValue': null,
            'createBy': null,
            'createTime': null,
            'updateBy': null,
            'updateTime': null,
            'remark': null,
            'params': null,
            'delFlag': null,
            'menuId': 2008,
            'menuName': 'echarts-6',
            'parentId': 4,
            'menuLevel': null,
            'orderNum': '4',
            'url': '/charts/echartsSix',
            'menuType': '0',
            'icon': null,
            'children': []
          }, {
            'searchValue': null,
            'createBy': null,
            'createTime': null,
            'updateBy': null,
            'updateTime': null,
            'remark': null,
            'params': null,
            'delFlag': null,
            'menuId': 2009,
            'menuName': 'echarts-7',
            'parentId': 4,
            'menuLevel': null,
            'orderNum': '4',
            'url': '/charts/echartsSeven',
            'menuType': '0',
            'icon': null,
            'children': []
          }, {
            'searchValue': null,
            'createBy': null,
            'createTime': null,
            'updateBy': null,
            'updateTime': null,
            'remark': null,
            'params': null,
            'delFlag': null,
            'menuId': 2011,
            'menuName': 'echarts-8',
            'parentId': 4,
            'menuLevel': null,
            'orderNum': '4',
            'url': '/charts/echartsEight',
            'menuType': '0',
            'icon': null,
            'children': []
          }, {
            'searchValue': null,
            'createBy': null,
            'createTime': null,
            'updateBy': null,
            'updateTime': null,
            'remark': null,
            'params': null,
            'delFlag': null,
            'menuId': 2010,
            'menuName': 'echarts-9',
            'parentId': 4,
            'menuLevel': null,
            'orderNum': '4',
            'url': '/charts/echartsNine',
            'menuType': '0',
            'icon': null,
            'children': []
          }]
      }
      const pageCharts2 = {
        'searchValue': null,
        'createBy': null,
        'createTime': '2020-11-11 11:37',
        'updateBy': null,
        'updateTime': null,
        'remark': null,
        'params': null,
        'delFlag': null,
        'menuId': 4,
        'menuName': 'echarts2',
        'parentId': 1,
        'menuLevel': null,
        'orderNum': '0',
        'url': '#7',
        'menuType': '0',
        'icon': 'el-icon-orange',
        'children': [
          {
            'searchValue': null,
            'createBy': null,
            'createTime': null,
            'updateBy': null,
            'updateTime': null,
            'remark': null,
            'params': null,
            'delFlag': null,
            'menuId': 7001,
            'menuName': 'echarts-1',
            'parentId': 4,
            'menuLevel': null,
            'orderNum': '4',
            'url': '/charts2/echartsOne',
            'menuType': '0',
            'icon': null,
            'children': []
          }, {
            'searchValue': null,
            'createBy': null,
            'createTime': null,
            'updateBy': null,
            'updateTime': null,
            'remark': null,
            'params': null,
            'delFlag': null,
            'menuId': 7002,
            'menuName': 'echarts-2',
            'parentId': 4,
            'menuLevel': null,
            'orderNum': '4',
            'url': '/charts2/echartsTwo',
            'menuType': '0',
            'icon': null,
            'children': []
          }, {
            'searchValue': null,
            'createBy': null,
            'createTime': null,
            'updateBy': null,
            'updateTime': null,
            'remark': null,
            'params': null,
            'delFlag': null,
            'menuId': 7003,
            'menuName': 'echarts-3',
            'parentId': 4,
            'menuLevel': null,
            'orderNum': '4',
            'url': '/charts2/echartsThree',
            'menuType': '0',
            'icon': null,
            'children': []
          }, {
            'searchValue': null,
            'createBy': null,
            'createTime': null,
            'updateBy': null,
            'updateTime': null,
            'remark': null,
            'params': null,
            'delFlag': null,
            'menuId': 7004,
            'menuName': 'echarts-4',
            'parentId': 4,
            'menuLevel': null,
            'orderNum': '4',
            'url': '/charts2/echartsFour',
            'menuType': '0',
            'icon': null,
            'children': []
          }, {
            'searchValue': null,
            'createBy': null,
            'createTime': null,
            'updateBy': null,
            'updateTime': null,
            'remark': null,
            'params': null,
            'delFlag': null,
            'menuId': 7005,
            'menuName': 'echarts-5',
            'parentId': 4,
            'menuLevel': null,
            'orderNum': '4',
            'url': '/charts2/echartsFive',
            'menuType': '0',
            'icon': null,
            'children': []
          }, {
            'searchValue': null,
            'createBy': null,
            'createTime': null,
            'updateBy': null,
            'updateTime': null,
            'remark': null,
            'params': null,
            'delFlag': null,
            'menuId': 7006,
            'menuName': 'echarts-6',
            'parentId': 4,
            'menuLevel': null,
            'orderNum': '4',
            'url': '/charts2/echartsSix',
            'menuType': '0',
            'icon': null,
            'children': []
          }, {
            'searchValue': null,
            'createBy': null,
            'createTime': null,
            'updateBy': null,
            'updateTime': null,
            'remark': null,
            'params': null,
            'delFlag': null,
            'menuId': 7007,
            'menuName': 'echarts-7',
            'parentId': 4,
            'menuLevel': null,
            'orderNum': '4',
            'url': '/charts2/echartsSeven',
            'menuType': '0',
            'icon': null,
            'children': []
          }, {
            'searchValue': null,
            'createBy': null,
            'createTime': null,
            'updateBy': null,
            'updateTime': null,
            'remark': null,
            'params': null,
            'delFlag': null,
            'menuId': 7008,
            'menuName': 'echarts-8',
            'parentId': 4,
            'menuLevel': null,
            'orderNum': '4',
            'url': '/charts2/echartsEight',
            'menuType': '0',
            'icon': null,
            'children': []
          }, {
            'searchValue': null,
            'createBy': null,
            'createTime': null,
            'updateBy': null,
            'updateTime': null,
            'remark': null,
            'params': null,
            'delFlag': null,
            'menuId': 7009,
            'menuName': 'echarts-9',
            'parentId': 4,
            'menuLevel': null,
            'orderNum': '4',
            'url': '/charts2/echartsNine',
            'menuType': '0',
            'icon': null,
            'children': []
          }]
      }
      const pageVue2 = {
        'searchValue': null,
        'createBy': null,
        'createTime': '2020-11-11 11:37',
        'updateBy': null,
        'updateTime': null,
        'remark': null,
        'params': null,
        'delFlag': null,
        'menuId': 4,
        'menuName': 'VUE2',
        'parentId': 1,
        'menuLevel': null,
        'orderNum': '0',
        'url': '#5',
        'menuType': '0',
        'icon': 'el-icon-watermelon',
        'children': [
          {
            'searchValue': null,
            'createBy': null,
            'createTime': null,
            'updateBy': null,
            'updateTime': null,
            'remark': null,
            'params': null,
            'delFlag': null,
            'menuId': 5001,
            'menuName': 'Render',
            'parentId': 4,
            'menuLevel': null,
            'orderNum': '4',
            'url': '/vue2/render',
            'menuType': '0',
            'icon': null,
            'children': []
          }, {
            'searchValue': null,
            'createBy': null,
            'createTime': null,
            'updateBy': null,
            'updateTime': null,
            'remark': null,
            'params': null,
            'delFlag': null,
            'menuId': 5002,
            'menuName': 'Slot',
            'parentId': 4,
            'menuLevel': null,
            'orderNum': '4',
            'url': '/vue2/slot',
            'menuType': '0',
            'icon': null,
            'children': []
          }]
      }
      const pageThreejs = {
        'searchValue': null,
        'createBy': null,
        'createTime': '2020-11-11 11:37',
        'updateBy': null,
        'updateTime': null,
        'remark': null,
        'params': null,
        'delFlag': null,
        'menuId': 4,
        'menuName': 'threejs',
        'parentId': 1,
        'menuLevel': null,
        'orderNum': '0',
        'url': '#8',
        'menuType': '0',
        'icon': 'el-icon-orange',
        'children': [
          {
            'searchValue': null,
            'createBy': null,
            'createTime': null,
            'updateBy': null,
            'updateTime': null,
            'remark': null,
            'params': null,
            'delFlag': null,
            'menuId': 8001,
            'menuName': 'threejs-1',
            'parentId': 4,
            'menuLevel': null,
            'orderNum': '4',
            'url': '/threejs/threejsOne',
            'menuType': '0',
            'icon': null,
            'children': []
          }, {
            'searchValue': null,
            'createBy': null,
            'createTime': null,
            'updateBy': null,
            'updateTime': null,
            'remark': null,
            'params': null,
            'delFlag': null,
            'menuId': 8002,
            'menuName': 'threejs-2',
            'parentId': 4,
            'menuLevel': null,
            'orderNum': '4',
            'url': '/threejs/threejsTwo',
            'menuType': '0',
            'icon': null,
            'children': []
          }, {
            'searchValue': null,
            'createBy': null,
            'createTime': null,
            'updateBy': null,
            'updateTime': null,
            'remark': null,
            'params': null,
            'delFlag': null,
            'menuId': 8003,
            'menuName': 'threejs-3',
            'parentId': 4,
            'menuLevel': null,
            'orderNum': '4',
            'url': '/threejs/threejsThree',
            'menuType': '0',
            'icon': null,
            'children': []
          }, {
            'searchValue': null,
            'createBy': null,
            'createTime': null,
            'updateBy': null,
            'updateTime': null,
            'remark': null,
            'params': null,
            'delFlag': null,
            'menuId': 8004,
            'menuName': 'threejs-4',
            'parentId': 4,
            'menuLevel': null,
            'orderNum': '4',
            'url': '/threejs/threejsFour',
            'menuType': '0',
            'icon': null,
            'children': []
          }, {
            'searchValue': null,
            'createBy': null,
            'createTime': null,
            'updateBy': null,
            'updateTime': null,
            'remark': null,
            'params': null,
            'delFlag': null,
            'menuId': 8005,
            'menuName': 'threejs-5',
            'parentId': 4,
            'menuLevel': null,
            'orderNum': '4',
            'url': '/threejs/threejsFive',
            'menuType': '0',
            'icon': null,
            'children': []
          }, {
            'searchValue': null,
            'createBy': null,
            'createTime': null,
            'updateBy': null,
            'updateTime': null,
            'remark': null,
            'params': null,
            'delFlag': null,
            'menuId': 8006,
            'menuName': 'threejs-6',
            'parentId': 4,
            'menuLevel': null,
            'orderNum': '4',
            'url': '/threejs/threejsSix',
            'menuType': '0',
            'icon': null,
            'children': []
          }, {
            'searchValue': null,
            'createBy': null,
            'createTime': null,
            'updateBy': null,
            'updateTime': null,
            'remark': null,
            'params': null,
            'delFlag': null,
            'menuId': 8007,
            'menuName': 'threejs-7',
            'parentId': 4,
            'menuLevel': null,
            'orderNum': '4',
            'url': '/threejs/threejsSeven',
            'menuType': '0',
            'icon': null,
            'children': []
          }, {
            'searchValue': null,
            'createBy': null,
            'createTime': null,
            'updateBy': null,
            'updateTime': null,
            'remark': null,
            'params': null,
            'delFlag': null,
            'menuId': 8008,
            'menuName': 'threejs-8',
            'parentId': 4,
            'menuLevel': null,
            'orderNum': '4',
            'url': '/threejs/threejsEight',
            'menuType': '0',
            'icon': null,
            'children': []
          }, {
            'searchValue': null,
            'createBy': null,
            'createTime': null,
            'updateBy': null,
            'updateTime': null,
            'remark': null,
            'params': null,
            'delFlag': null,
            'menuId': 8009,
            'menuName': 'threejs-9',
            'parentId': 4,
            'menuLevel': null,
            'orderNum': '4',
            'url': '/threejs/threejsNine',
            'menuType': '0',
            'icon': null,
            'children': []
          }, {
            'searchValue': null,
            'createBy': null,
            'createTime': null,
            'updateBy': null,
            'updateTime': null,
            'remark': null,
            'params': null,
            'delFlag': null,
            'menuId': 8010,
            'menuName': 'threejs-10',
            'parentId': 4,
            'menuLevel': null,
            'orderNum': '4',
            'url': '/threejs/threejsTen',
            'menuType': '0',
            'icon': null,
            'children': []
          }]
      }
      this.menuList.push(pageShow, pageComponents, pageVue, pageVue2, pageCharts, pageCharts2, pageThreejs)
    }
  }
}
</script>

<style>
.el-menu--inline .el-submenu__title {
  background: #1f2d3d !important;
}
.el-submenu [class^="el-icon-"] {
  margin: 15px;
}
</style>
